import { article, PrismaClient } from ".prisma/client";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

type Article = {
  id: number;
  title: string;
  body: string;
  snippet: string;
};

type Props = {
  articles: Article[];
};

const Home = ({ articles }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Articles</h1>
        <ul>
          {articles.map((article) => (
            <li key={`article-${article.id}`}>
              {article.title} <span>{article.snippet}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const client = new PrismaClient();

  const articles = await client.article.findMany({
    take: 10,
    select: {
      id: true,
      snippet: true,
      title: true,
      body: true,
    },
  });

  return {
    props: {
      articles: articles.map((item) => ({
        ...item,
        body: item.body.toString(),
      })),
    },
  };
};
